import type { Metadata } from "next";
import { Geist, Geist_Mono, Poppins } from "next/font/google";
import "./globals.css";
import Footer from "@/components/footer";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const poppinFont = Poppins({
  weight: "500",
  subsets: ["latin"]
})

export const metadata: Metadata = {
  title: "Analytics Pro",
  description: "Not generated by next app.",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="bg-white">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${poppinFont.className} antialiased`}
      >
        {children}
      </body>
      <Footer/>
    </html>
  );
}
