FROM node:18.14.2-alpine

ARG NEON_DB_URL
ENV NEON_DB_URL=$NEON_DB_URL

WORKDIR /usr/local/queue-worker

COPY apps/queue-worker/ ./

RUN npm install

# RUN npm run drizzle-push

RUN npm run build
RUN rm -rf ./src

CMD [ "npm", "start" ]