FROM node:18.14.2-alpine

WORKDIR /event-processor

COPY event-processor/* ./

COPY scripts/*.sh ./

RUN chmod +x ./wait-for-it.sh

RUN npm install

RUN npm run build

RUN rm -rf /src

CMD [ "npm", "start" ]