CREATE TABLE "raw_analytics" (
	"id" integer PRIMARY KEY GENERATED ALWAYS AS IDENTITY (sequence name "raw_analytics_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"country_code" varchar,
	"lang_region" varchar,
	"lang_language" varchar,
	"added_unix" integer NOT NULL,
	"added_date" varchar NOT NULL,
	"added_iso" varchar NOT NULL,
	"is_robot" boolean NOT NULL,
	"hostname" varchar NOT NULL,
	"hostname_original" varchar,
	"path" varchar NOT NULL,
	"utm_source" varchar,
	"utm_medium" varchar,
	"utm_campaign" varchar,
	"utm_content" varchar,
	"utm_term" varchar,
	"referrer" varchar,
	"document_referrer" varchar,
	"browser_name" varchar,
	"browser_version" varchar,
	"os_name" varchar,
	"os_version" varchar,
	"device_type" varchar,
	"user_agent" varchar NOT NULL,
	"ip_address" varchar,
	"viewport_height" integer,
	"viewport_width" integer,
	"screen_width" integer,
	"screen_height" integer
);
